services:
  database:
    container_name: Postgres-DB
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'tmu_connect'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tmu_connect" ]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pg-db:/var/lib/postgresql/data
      - ./server/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_cache:/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitor:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=127.0.0.1:9090'
    network_mode: "host"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitor/dashboard:/etc/grafana/provisioning
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_HTTP_ADDR=127.0.0.1
      - GF_SERVER_HTTP_PORT=3030
    depends_on:
      - prometheus
    network_mode: "host"
volumes:
  minio:
    driver: local
  pg-db:
    driver: local
  redis_cache:
    driver: local
  prometheus_data:
    driver: local
  grafana_storage:
    driver: local
