services:
  database:
    container_name: Postgres-DB
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'tmu_connect'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tmu_connect" ]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pg-db:/var/lib/postgresql/data
      - ./server/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pg-db:
